Make readManifest something that we can stub
- Existing tests and code updated for namespace
- New test fails with:
  Error: Nock: No match for request {
    method: get,
    url: https://addons.heroku.com/provider/addons/undefined,
    ...

  which is the case where we want commands to fail earlier rather than
  try to run requests for an undefined slug